import type { DictEntry } from "./text";
import type { Accelerator, Arch, Libc, OS, Runtime } from "./types";

export const OS_DICT: DictEntry<OS>[] = [
  {
    id: "windows",
    strong: [
      "windows",
      "win32",
      "win64",
      "winnt",
      "pc-windows",
      "windows-msvc",
      "windows-gnu",
      "mingw64",
      "mingw32",
      "mingw",
      "cygwin",
      "winarm64",
      "windowsserver",
      "windows-store",
    ],
    weak: ["win", "w64", "w32", "msvc", "winx64", "winx86"],
  },
  {
    id: "macos",
    strong: [
      "macos",
      "macosx",
      "mac-os-x",
      "apple-darwin",
      "darwin",
      "osx",
      "macintosh",
      "os-x",
      "mac",
    ],
    weak: ["apple", "osx64", "mac64"],
  },
  {
    id: "linux",
    strong: [
      "linux",
      "unknown-linux",
      "linux-gnu",
      "linux-musl",
      "gnu-linux",
      "linux64",
      "linux32",
    ],
    weak: [],
  },
  { id: "android", strong: ["android", "androidtv", "wearos"], weak: [] },
  {
    id: "ios",
    strong: ["ios", "iphoneos", "ipados", "tvos", "watchos"],
    weak: [],
  },
  { id: "freebsd", strong: ["freebsd"], weak: [] },
  { id: "openbsd", strong: ["openbsd"], weak: [] },
  { id: "netbsd", strong: ["netbsd", "dragonfly", "dragonflybsd"], weak: [] },
  {
    id: "solaris",
    strong: ["solaris", "illumos", "sunos", "smartos"],
    weak: [],
  },
  {
    id: "wasm",
    strong: ["wasm32", "wasm64", "webassembly", "emscripten", "wasi", "wasm"],
    weak: [],
  },
];

/** Distros imply Linux and are worth surfacing in the UI. */
export const DISTRO_DICT: DictEntry<string>[] = [
  { id: "ubuntu", strong: ["ubuntu", "jammy", "noble", "focal", "bionic"] },
  {
    id: "debian",
    strong: ["debian", "bookworm", "bullseye", "buster", "trixie"],
  },
  { id: "fedora", strong: ["fedora"] },
  {
    id: "rhel",
    strong: [
      "rhel",
      "redhat",
      "el7",
      "el8",
      "el9",
      "centos",
      "rocky",
      "almalinux",
    ],
  },
  { id: "suse", strong: ["opensuse", "suse", "sles"] },
  { id: "alpine", strong: ["alpine"] },
  { id: "arch", strong: ["archlinux", "arch-linux"] },
  { id: "raspbian", strong: ["raspbian", "raspberrypi", "raspberry-pi"] },
  { id: "nixos", strong: ["nixos"] },
  { id: "steamos", strong: ["steamos", "steamdeck"] },
];

export const ARCH_DICT: DictEntry<Arch>[] = [
  {
    id: "x64",
    strong: [
      "x86-64",
      "x86_64",
      "x8664",
      "amd64",
      "x64",
      "win64",
      "linux64",
      "osx64",
      "mac64",
      "64bit",
      "64-bit",
      "intel64",
      "x86-64-v2",
      "x86-64-v3",
      "x86-64-v4",
    ],
    weak: ["intel"],
  },
  {
    id: "x86",
    strong: [
      "i386",
      "i486",
      "i586",
      "i686",
      "ia32",
      "win32",
      "x86",
      "linux32",
      "32bit",
      "32-bit",
      "386",
    ],
    weak: [],
  },
  {
    id: "arm64",
    strong: [
      "aarch64",
      "arm64-v8a",
      "arm64ec",
      "arm64e",
      "arm64",
      "armv8",
      "armv8a",
      "aarch-64",
      "apple-silicon",
      "applesilicon",
    ],
    weak: ["silicon", "m1", "m2", "m3", "m4"],
  },
  {
    id: "arm",
    strong: [
      "armeabi-v7a",
      "armeabi",
      "armv7hl",
      "armv7l",
      "armv7a",
      "armv7",
      "armv6l",
      "armv6",
      "armhf",
      "armel",
      "arm32",
    ],
    weak: ["arm"],
  },
  {
    id: "riscv64",
    strong: ["riscv64gc", "riscv64", "rv64gc", "rv64"],
    weak: ["riscv"],
  },
  { id: "ppc64le", strong: ["ppc64le", "powerpc64le"], weak: [] },
  { id: "ppc64", strong: ["ppc64", "powerpc64"], weak: ["ppc", "powerpc"] },
  { id: "s390x", strong: ["s390x"], weak: ["s390"] },
  { id: "mips64", strong: ["mips64el", "mips64le", "mips64"], weak: [] },
  { id: "mips", strong: ["mipsel", "mipsle", "mips"], weak: [] },
  { id: "loong64", strong: ["loongarch64", "loong64"], weak: [] },
  { id: "sparc64", strong: ["sparc64"], weak: ["sparc"] },
  {
    id: "universal",
    strong: [
      "universal2",
      "universal-2",
      "universal",
      "multiarch",
      "noarch",
      "fat-binary",
    ],
    weak: [],
  },
];

export const LIBC_DICT: DictEntry<Libc>[] = [
  {
    id: "musl",
    strong: ["musl", "musleabi", "musleabihf", "linux-musl", "static-musl"],
  },
  { id: "gnu", strong: ["gnu", "glibc", "gnueabi", "gnueabihf", "linux-gnu"] },
  { id: "uclibc", strong: ["uclibc"] },
];

export const ACCELERATOR_DICT: DictEntry<Accelerator>[] = [
  {
    id: "cuda",
    strong: [
      "cuda",
      "cuda11",
      "cuda12",
      "cuda13",
      "cu118",
      "cu121",
      "cu124",
      "cu126",
      "nvidia",
      "cudnn",
      "tensorrt",
    ],
  },
  { id: "rocm", strong: ["rocm", "rocm5", "rocm6"] },
  { id: "hip", strong: ["hipblas", "hip"] },
  { id: "vulkan", strong: ["vulkan", "kompute"] },
  { id: "metal", strong: ["metal", "mps"] },
  { id: "opencl", strong: ["opencl", "clblast"] },
  { id: "directml", strong: ["directml", "dml"] },
  { id: "openvino", strong: ["openvino"] },
  { id: "sycl", strong: ["sycl", "oneapi"] },
  { id: "npu", strong: ["npu", "qnn", "hexagon", "rknn"] },
  {
    id: "cpu",
    strong: ["cpu-only", "cpuonly", "noavx", "avx2", "avx512", "avx", "cpu"],
  },
];

export const RUNTIME_DICT: DictEntry<Runtime>[] = [
  { id: "jre", strong: ["with-jre", "jre", "bundled-jre"] },
  { id: "jdk", strong: ["with-jdk", "jdk"] },
  {
    id: "dotnet",
    strong: [
      "dotnet",
      "net8",
      "net9",
      "net6",
      "net7",
      "netcore",
      "framework-dependent",
      "self-contained",
    ],
  },
  { id: "node", strong: ["nodejs", "node"] },
  { id: "python", strong: ["python3", "python", "cpython", "py3"] },
  { id: "electron", strong: ["electron"] },
  { id: "mono", strong: ["mono"] },
];

/**
 * Longest-first is enforced at match time. Compound extensions must be listed
 * so that `.pkg.tar.zst` is never read as a macOS `.pkg`.
 */
export const EXTENSIONS: string[] = [
  ".pkg.tar.zst",
  ".pkg.tar.xz",
  ".pkg.tar.gz",
  ".tar.gz",
  ".tar.xz",
  ".tar.bz2",
  ".tar.zst",
  ".tar.lz4",
  ".tar.br",
  ".tar.lz",
  ".app.zip",
  ".dsym.zip",
  ".symbols.zip",
  ".appxbundle",
  ".msixbundle",
  ".appinstaller",
  ".flatpakref",
  ".sigstore.json",
  ".intoto.jsonl",
  ".spdx.json",
  ".cdx.json",
  ".sbom.json",
  ".tgz",
  ".txz",
  ".tbz2",
  ".tar",
  ".zip",
  ".7z",
  ".rar",
  ".gz",
  ".xz",
  ".bz2",
  ".zst",
  ".lz4",
  ".exe",
  ".msi",
  ".msix",
  ".appx",
  ".dmg",
  ".pkg",
  ".app",
  ".deb",
  ".rpm",
  ".appimage",
  ".snap",
  ".flatpak",
  ".apk",
  ".aab",
  ".ipa",
  ".xpi",
  ".crx",
  ".nupkg",
  ".jar",
  ".war",
  ".whl",
  ".gem",
  ".phar",
  ".sif",
  ".vsix",
  ".blockmap",
  ".yml",
  ".yaml",
  ".json",
  ".jsonl",
  ".xml",
  ".plist",
  ".txt",
  ".md",
  ".pdf",
  ".html",
  ".sha256sum",
  ".sha512sum",
  ".sha256",
  ".sha512",
  ".sha1",
  ".md5",
  ".sum",
  ".digest",
  ".sig",
  ".asc",
  ".gpg",
  ".pem",
  ".crt",
  ".cert",
  ".p7s",
  ".minisig",
  ".sigstore",
  ".sarif",
  ".spdx",
  ".cdx",
  ".att",
  ".pdb",
  ".dsym",
  ".sym",
  ".dwp",
  ".debug",
  ".map",
  ".bin",
  ".img",
  ".iso",
  ".efi",
  ".elf",
  ".so",
  ".dll",
  ".dylib",
  ".ko",
  ".uf2",
  ".hex",
  ".srec",
  ".wasm",
  ".run",
  ".sh",
  ".ps1",
  ".bat",
].sort((a, b) => b.length - a.length);

export const OS_LABEL: Record<OS, string> = {
  windows: "Windows",
  macos: "macOS",
  linux: "Linux",
  android: "Android",
  ios: "iOS",
  freebsd: "FreeBSD",
  openbsd: "OpenBSD",
  netbsd: "NetBSD",
  solaris: "Solaris",
  wasm: "WebAssembly",
};

export const ARCH_LABEL: Record<Arch, string> = {
  x64: "x64",
  x86: "x86",
  arm64: "arm64",
  arm: "arm",
  riscv64: "riscv64",
  ppc64le: "ppc64le",
  ppc64: "ppc64",
  s390x: "s390x",
  mips64: "mips64",
  mips: "mips",
  loong64: "loong64",
  sparc64: "sparc64",
  universal: "universal",
};

export const OS_DISPLAY_ORDER: OS[] = [
  "windows",
  "macos",
  "linux",
  "android",
  "ios",
  "freebsd",
  "openbsd",
  "netbsd",
  "solaris",
  "wasm",
];

/** Extension → the only OS it can possibly belong to. */
export const EXTENSION_OS: Record<string, OS> = {
  ".exe": "windows",
  ".msi": "windows",
  ".msix": "windows",
  ".msixbundle": "windows",
  ".appx": "windows",
  ".appxbundle": "windows",
  ".appinstaller": "windows",
  ".dll": "windows",
  ".bat": "windows",
  ".ps1": "windows",
  ".dmg": "macos",
  ".pkg": "macos",
  ".app": "macos",
  ".app.zip": "macos",
  ".dsym.zip": "macos",
  ".dylib": "macos",
  ".deb": "linux",
  ".rpm": "linux",
  ".appimage": "linux",
  ".snap": "linux",
  ".flatpak": "linux",
  ".flatpakref": "linux",
  ".pkg.tar.zst": "linux",
  ".pkg.tar.xz": "linux",
  ".pkg.tar.gz": "linux",
  ".so": "linux",
  ".ko": "linux",
  ".apk": "android",
  ".aab": "android",
  ".ipa": "ios",
  ".wasm": "wasm",
};

/** How pleasant each container is for a non-technical user, per OS. */
export const FORMAT_PREFERENCE: Record<OS, Record<string, number>> = {
  windows: {
    ".exe": 0.95,
    ".msi": 0.92,
    ".msix": 0.72,
    ".appx": 0.62,
    ".msixbundle": 0.6,
    ".appinstaller": 0.5,
    ".zip": 0.78,
    ".7z": 0.6,
    ".tar.gz": 0.45,
    ".tar.xz": 0.42,
    ".nupkg": 0.2,
  },
  macos: {
    ".dmg": 1.0,
    ".pkg": 0.9,
    ".app.zip": 0.85,
    ".zip": 0.8,
    ".tar.gz": 0.62,
    ".tar.xz": 0.6,
    ".7z": 0.4,
  },
  linux: {
    ".appimage": 0.95,
    ".deb": 0.88,
    ".rpm": 0.82,
    ".tar.gz": 0.76,
    ".tar.xz": 0.74,
    ".tar.zst": 0.7,
    ".tgz": 0.72,
    ".zip": 0.55,
    ".flatpak": 0.6,
    ".snap": 0.55,
    ".pkg.tar.zst": 0.5,
    ".run": 0.6,
    ".sh": 0.45,
    ".bin": 0.6,
  },
  android: { ".apk": 1.0, ".aab": 0.15 },
  ios: { ".ipa": 1.0 },
  freebsd: { ".tar.gz": 0.9, ".txz": 0.85, ".pkg": 0.8, ".zip": 0.5 },
  openbsd: { ".tar.gz": 0.9, ".tgz": 0.85, ".zip": 0.5 },
  netbsd: { ".tar.gz": 0.9, ".tgz": 0.85, ".zip": 0.5 },
  solaris: { ".tar.gz": 0.9, ".zip": 0.5 },
  wasm: { ".wasm": 1.0, ".tar.gz": 0.6, ".zip": 0.6 },
};
